### ISSUE TITLE
[Feature Request] Auto-assign shop titles

### ISSUE THREAD

**Issue by MysticMismagius** [FortuneStreetModding/fortune-avenue-qt#9]
Would probably be in the tools section like autopath

Basically it would assign every shop on the map a title (or "model" as it's called in FA) randomly from ID 1-100 (10G-1000G). There would be an option to only include titles used in vanilla, and an option to prevent duplicate titles

**Comment by Sophilautia** [comment]
Rather than randomly, I feel like it would be best if it assigned a shop model based on the closest value.  ie. If the shop starting price is 820g, it would select Bridal Boutique.

**Comment by ZaSpai** [comment]
I'm thinking about the possible utility for this for future yaml-modifiable shop model names, since if the IDs are all defined as per their assumed shop values (so of those defined already in FA, IDs 5-59, 61-62, 65, 68, 70, 72, 75-76, 80, 81, 85, 90, 98) they can be called quite readily in the yaml file.
In terms of 'default' names I'd probably go with what Sophi suggested to choose the closest existing option. Otherwise we'd probably need to look into a community / FA 'default' set of names for the undefined IDs.
I'd also want for the option to unassign the standard pairing of model name to shop preset, i.e. if you really wanted to use shop IDs 1-40 and don't use associated shop values from 50-400G, you don't have to.

**Comment by MysticMismagius** [comment]
The reason I suggested setting shop titles randomly is because I have a particular way I like shops to be named: I want each shop on the board to have a different name (not including Department Stores created from 3-star shops), and I don't care that specific shop values are linked to specific names in FSWii.

**Comment by Sophilautia** [comment]
Personally, I would like a feature that doesn't do it randomly, but assigns shops a shop title based on the value of the shop. There's a lot of boards (especially by Kirby) that just didn't include shop titles, and a simple script would make fixing that so much easier, and save many hours of fiddling.

**Comment by Deflaktor** [comment]
solved with 98064da43542da4ab34c50f60e49a637765d5fcc
